### PR TITLE
Add Martian Mono

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello @romashamin!

The font is exported and works very well.
I just corrected the zero that had a problem with the bar.
Capture d’écran 2022-11-25 à 09 51 33

I'll let you have a look at the QA to see if everything is ok.
[MartianMono_QA.zip](https://github.com/evilmartians/mono/files/10090148/MartianMono_QA.zip)

I copied my GF file with your parameters, so you can export it on your side with your own instances names.
I'm waiting for your feedback, don't hesitate if you have any questions! :)

Cheers!
Emma

### CODE REVIEW

**Comment by romashamin** [comment]
> I just corrected the zero that had a problem with the bar

That’s what I missed! @emmamarichal thank you for finding this 😊

Will check the QA and the rest asap.

**Comment by romashamin** [comment]
@emmamarichal found one: something is wrong with greater/less glyphs
Screen Shot 2022-11-25 at 12 43 06

**Comment by emmamarichal** [comment]
Ah exact, I'm correcting it, it's quick (it was made with components)
Tell me if you see some other bugs, I'll send you a new PR!

**Comment by romashamin** [comment]
I believe other glyphs look good.
Screen Shot 2022-11-25 at 13 57 20
Screen Shot 2022-11-25 at 13 57 57

**Pull request merged**
